# Generated by Django 3.0.8 on 2020-08-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_notifications', '0003_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='email',
            field=models.BooleanField(
                help_text='note: non-superadmin users receive notifications only for organizations of which they are member of.',
                null=True,
                verbose_name='email notifications',
            ),
        ),
    ]
