# Generated by Django 3.1.4 on 2020-12-24 08:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openwisp_notifications', '0006_objectnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'web',
                    models.BooleanField(
                        blank=True,
                        help_text='Note: If Yes is selected, User will not recieve any notifications. ',
                        null=True,
                        verbose_name='disable web notifications',
                    ),
                ),
                (
                    'email',
                    models.BooleanField(
                        blank=True,
                        help_text='Note: If Yes is selected, User will not recieve any notifications. ',
                        null=True,
                        verbose_name='disable email notifications',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'general settings',
                'verbose_name_plural': 'general settings',
                'ordering': ['user'],
                'abstract': False,
                'swappable': 'OPENWISP_NOTIFICATIONS_GENERALSETTING_MODEL',
            },
        ),
    ]
