# Generated by Django 4.2.19 on 2025-02-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openwisp_notifications", "0007_notificationsetting_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
