# Generated by Django 4.2 on 2025-02-01 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("openwisp_users", "0020_populate_password_updated_field"),
        ("openwisp_notifications", "0007_notificationsetting_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("email_notifications_enabled", models.BooleanField(default=True)),
            ],
        ),
    ]
