# Generated by Django 4.2.16 on 2024-09-17 13:19

import django
import django.db.models.deletion
from django.db import migrations, models

from openwisp_notifications.types import NOTIFICATION_CHOICES, get_notification_choices


class Migration(migrations.Migration):
    dependencies = [
        ("openwisp_users", "0020_populate_password_updated_field"),
        (
            "openwisp_notifications",
            "0008_rename_notification_recipient_unread_openwisp_no_recipie_b7c4ef_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationsetting",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="openwisp_users.organization",
            ),
        ),
        migrations.AlterField(
            model_name="notificationsetting",
            name="type",
            field=models.CharField(
                blank=True,
                choices=NOTIFICATION_CHOICES
                if django.VERSION < (5, 0)
                else get_notification_choices,
                max_length=30,
                null=True,
                verbose_name="Notification Type",
            ),
        ),
    ]
