# Generated by Django 4.2.23 on 2025-07-02 10:19

import django.db.models.deletion
from django.db import migrations, models

import openwisp_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_users", "0021_rename_user_id_email_openwisp_us_id_06c07a_idx"),
        (
            "openwisp_notifications",
            "0009_alter_notificationsetting_organization_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationNotificationSettings",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="notification_settings",
                        serialize=False,
                        to="openwisp_users.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "web",
                    openwisp_utils.fields.FallbackBooleanChoiceField(
                        blank=True,
                        default=None,
                        fallback=True,
                        help_text="Whether the web notifications are enabled",
                        null=True,
                        verbose_name="Web notifications enabled",
                    ),
                ),
                (
                    "email",
                    openwisp_utils.fields.FallbackBooleanChoiceField(
                        blank=True,
                        default=None,
                        fallback=True,
                        help_text="Whether the email notifications are enabled",
                        null=True,
                        verbose_name="Email notifications enabled",
                    ),
                ),
                (
                    "email_batch_interval",
                    openwisp_utils.fields.FallbackPositiveIntegerField(
                        blank=True,
                        default=None,
                        fallback=10800,
                        help_text="Email batch interval in seconds",
                        null=True,
                        verbose_name="Email batch interval",
                    ),
                ),
                (
                    "email_batch_display_limit",
                    openwisp_utils.fields.FallbackPositiveIntegerField(
                        blank=True,
                        default=None,
                        fallback=15,
                        help_text="Maximum number of notifications to display in batch email",
                        null=True,
                        verbose_name="Batch email display limit",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "OPENWISP_NOTIFICATIONS_ORGANIZATIONNOTIFICATIONSETTINGS_MODEL",
            },
        ),
    ]
