# Generated by Django 4.2.23 on 2025-07-02 10:19

import django.db.models.deletion
from django.db import migrations, models

import openwisp_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_users", "0021_rename_user_id_email_openwisp_us_id_06c07a_idx"),
        (
            "openwisp_notifications",
            "0009_alter_notificationsetting_organization_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationNotificationSettings",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="notification_settings",
                        serialize=False,
                        to="openwisp_users.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "web",
                    openwisp_utils.fields.FallbackBooleanChoiceField(
                        blank=True,
                        default=None,
                        fallback=True,
                        help_text=(
                            "Changing this value will affect the web notification settings of all "
                            "users in the organization. Users will still be able to override "
                            "this setting in their personal preferences."
                        ),
                        null=True,
                        verbose_name="Web notifications enabled",
                    ),
                ),
                (
                    "email",
                    openwisp_utils.fields.FallbackBooleanChoiceField(
                        blank=True,
                        default=None,
                        fallback=True,
                        help_text=(
                            "Changing this value will affect the email notification settings of all "
                            "users in the organization. Users will still be able to override "
                            "this setting in their personal preferences."
                        ),
                        null=True,
                        verbose_name="Email notifications enabled",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "organization notification settings",
                "verbose_name_plural": "organization notification settings",
                "swappable": "OPENWISP_NOTIFICATIONS_ORGANIZATIONNOTIFICATIONSETTINGS_MODEL",
            },
        ),
    ]
