# Generated by Django 4.2 on 2025-02-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "openwisp_notifications",
            "0009_remove_userprofile_email_notifications_enabled_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email_verified",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="needs_verification",
            field=models.BooleanField(default=False),
        ),
    ]
