# Generated by Django 4.2.23 on 2025-07-02 10:19

from django.db import migrations

from . import (
    assign_organizationnotificationsettings_permissions_to_groups,
    create_organization_notification_settings,
    reverse_create_organization_notification_settings,
)


class Migration(migrations.Migration):

    dependencies = [
        (
            "openwisp_notifications",
            "0010_organizationnotificationsettings",
        ),
    ]

    operations = [
        migrations.RunPython(
            create_organization_notification_settings,
            reverse_code=reverse_create_organization_notification_settings,
        ),
        migrations.RunPython(
            assign_organizationnotificationsettings_permissions_to_groups,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
