# Generated by Django 4.2.23 on 2025-07-02 10:19

from django.db import migrations

from . import assign_organizationnotificationsettings_permissions_to_groups


def create_organization_notification_settings(apps, schema_editor):
    OrganizationNotificationSettings = apps.get_model(
        "openwisp_notifications", "OrganizationNotificationSettings"
    )
    Organization = apps.get_model("openwisp_users", "Organization")

    for org in Organization.objects.iterator():
        org_setting = OrganizationNotificationSettings(organization=org)
        org_setting.full_clean()
        org_setting.save()


def reverse_create_organization_notification_settings(apps, schema_editor):
    OrganizationNotificationSettings = apps.get_model(
        "openwisp_notifications", "OrganizationNotificationSettings"
    )
    OrganizationNotificationSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "openwisp_notifications",
            "0010_organizationnotificationsettings",
        ),
    ]

    operations = [
        migrations.RunPython(
            create_organization_notification_settings,
            reverse_code=reverse_create_organization_notification_settings,
        ),
        migrations.RunPython(
            assign_organizationnotificationsettings_permissions_to_groups,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
