# Generated by Django 5.2.6 on 2025-10-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_notifications", "0011_populate_organizationnotificationsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="verb"
            ),
        ),
    ]
