# Generated by Django 5.2.6 on 2025-10-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_notifications", "0011_populate_organizationnotificationsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="verb",
        ),
    ]
