# Generated by Django 5.2.6 on 2026-01-31 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_notifications", "0012_alter_notification_verb"),
        ("openwisp_notifications", "0012_replace_jsonfield_with_django_builtin"),
    ]

    operations = []
