# Generated by Django 5.2.6 on 2025-10-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_notifications", "0012_alter_notification_verb_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="verb",
        ),
    ]
