# Generated by Django 3.0.6 on 2020-06-15 20:56

import uuid

import django.db.models.deletion
import swapper
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('openwisp_users', '0007_unique_email'),
        ('sample_notifications', '0001_initial'),
        swapper.dependency('openwisp_users', 'Organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestApp',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=swapper.get_model_name('openwisp_users', 'Organization'),
                    ),
                ),
            ],
            options={'verbose_name': 'Test App', 'verbose_name_plural': 'Test App'},
        ),
    ]
