# Generated by Django 5.2.6 on 2025-10-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sample_notifications", "0003_default_groups_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="verb",
        ),
    ]
