# Generated by Django 6.0.1 on 2026-01-30 18:10
from django.core.serializers.json import DjangoJSONEncoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_notifications", "0003_default_groups_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="data", encoder=DjangoJSONEncoder
            ),
        ),
    ]
