# Generated by Django 5.2.6 on 2026-01-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sample_notifications", "0004_alter_notification_verb"),
        ("sample_notifications", "0004_replace_jsonfield_with_django_builtin"),
    ]

    operations = []
